#!/bin/bash

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if running with root privileges
if [[ $EUID -ne 0 ]]; then
    echo -e "${RED}Error: This script must be run as root${NC}"
    echo "Please use: sudo $0"
    exit 1
fi

echo -e "${YELLOW}=== APT Mirror Change to Swedish Bahnhof ===${NC}"

# Detect Ubuntu version
UBUNTU_CODENAME=$(lsb_release -cs)
if [[ -z "$UBUNTU_CODENAME" ]]; then
    echo -e "${RED}Error: Could not detect Ubuntu version${NC}"
    exit 1
fi

echo -e "${GREEN}Detected Ubuntu version: $UBUNTU_CODENAME${NC}"

# Create timestamped backup
BACKUP_FILE="/etc/apt/sources.list.backup.$(date +%Y-%m-%d_%H-%M-%S)"
echo -e "${YELLOW}Creating backup: $BACKUP_FILE${NC}"

if ! cp /etc/apt/sources.list "$BACKUP_FILE"; then
    echo -e "${RED}Error: Failed to create backup${NC}"
    exit 1
fi

echo -e "${GREEN}Backup created successfully${NC}"

# Create new sources.list with Bahnhof mirror
BAHNHOF_MIRROR="http://mirror.bahnhof.net/ubuntu/"
COMPONENTS="main restricted universe multiverse"

echo -e "${YELLOW}Configuring APT sources to use Bahnhof mirror...${NC}"

cat > /etc/apt/sources.list << EOF
# Swedish Bahnhof mirror sources
# Generated by change-apt-mirror.sh

# Base repository
deb $BAHNHOF_MIRROR $UBUNTU_CODENAME $COMPONENTS
deb-src $BAHNHOF_MIRROR $UBUNTU_CODENAME $COMPONENTS

# Updates repository
deb $BAHNHOF_MIRROR $UBUNTU_CODENAME-updates $COMPONENTS
deb-src $BAHNHOF_MIRROR $UBUNTU_CODENAME-updates $COMPONENTS

# Security repository
deb $BAHNHOF_MIRROR $UBUNTU_CODENAME-security $COMPONENTS
deb-src $BAHNHOF_MIRROR $UBUNTU_CODENAME-security $COMPONENTS

# Backports repository
deb $BAHNHOF_MIRROR $UBUNTU_CODENAME-backports $COMPONENTS
deb-src $BAHNHOF_MIRROR $UBUNTU_CODENAME-backports $COMPONENTS
EOF

echo -e "${GREEN}APT sources configured${NC}"

# Update package lists to validate configuration
echo -e "${YELLOW}Updating package lists...${NC}"
if apt update; then
    echo -e "${GREEN}Package lists updated successfully${NC}"
else
    echo -e "${RED}Warning: apt update failed${NC}"
    echo -e "${YELLOW}Rolling back to original sources.list...${NC}"
    cp "$BACKUP_FILE" /etc/apt/sources.list
    apt update
    echo -e "${RED}Rollback completed. APT sources restored.${NC}"
    exit 1
fi

# Display success message
echo -e "${GREEN}✓ APT mirror successfully changed to Swedish Bahnhof${NC}"
echo ""
echo -e "${YELLOW}Configuration Summary:${NC}"
echo "  Mirror: $BAHNHOF_MIRROR"
echo "  Ubuntu: $UBUNTU_CODENAME"
echo "  Components: $COMPONENTS"
echo "  Backup: $BACKUP_FILE"
echo ""
echo -e "${YELLOW}To rollback to original sources.list:${NC}"
echo "  sudo cp $BACKUP_FILE /etc/apt/sources.list"
echo "  sudo apt update"
