#!/bin/bash

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Check if running with root privileges
if [[ $EUID -ne 0 ]]; then
    echo -e "${RED}Error: This script must be run as root${NC}"
    echo "Please use: sudo $0"
    exit 1
fi

echo -e "${YELLOW}=== inotify Limit Fix for dotnet watch ===${NC}"
echo ""

# Configuration file for persistent changes
SYSCTL_CONFIG_FILE="/etc/sysctl.d/99-inotify-limits.conf"

# New inotify limits
NEW_MAX_USER_WATCHES=524288
NEW_MAX_USER_INSTANCES=512
NEW_MAX_QUEUED_EVENTS=32768

# Display current limits
echo -e "${BLUE}Current inotify limits:${NC}"
CURRENT_WATCHES=$(sysctl -n fs.inotify.max_user_watches 2>/dev/null || echo "8192")
CURRENT_INSTANCES=$(sysctl -n fs.inotify.max_user_instances 2>/dev/null || echo "128")
CURRENT_QUEUED=$(sysctl -n fs.inotify.max_queued_events 2>/dev/null || echo "16384")

echo "  max_user_watches:    $CURRENT_WATCHES (default: 8192)"
echo "  max_user_instances:  $CURRENT_INSTANCES (default: 128) ← dotnet watch error occurs here"
echo "  max_queued_events:   $CURRENT_QUEUED (default: 16384)"
echo ""

# Create backup if config file already exists
if [[ -f "$SYSCTL_CONFIG_FILE" ]]; then
    BACKUP_FILE="${SYSCTL_CONFIG_FILE}.backup.$(date +%Y-%m-%d_%H-%M-%S)"
    echo -e "${YELLOW}Creating backup: $BACKUP_FILE${NC}"
    if ! cp "$SYSCTL_CONFIG_FILE" "$BACKUP_FILE"; then
        echo -e "${RED}Error: Failed to create backup${NC}"
        exit 1
    fi
    echo -e "${GREEN}Backup created successfully${NC}"
else
    echo -e "${YELLOW}No existing inotify config found, creating new file${NC}"
fi

echo ""
echo -e "${YELLOW}Applying new inotify limits...${NC}"

# Create the sysctl configuration file
cat > "$SYSCTL_CONFIG_FILE" << EOF
# inotify limits configuration for development tools
# Generated by fix-inotify-limit.sh
#
# These limits are increased to support file watchers used by:
# - dotnet watch
# - npm/yarn watch
# - webpack
# - other development tools that monitor many files

# Maximum number of file descriptors that can be associated with a watcher
fs.inotify.max_user_watches = $NEW_MAX_USER_WATCHES

# Maximum number of inotify instances per user
fs.inotify.max_user_instances = $NEW_MAX_USER_INSTANCES

# Maximum number of events that can be queued
fs.inotify.max_queued_events = $NEW_MAX_QUEUED_EVENTS
EOF

if [[ $? -ne 0 ]]; then
    echo -e "${RED}Error: Failed to write configuration file${NC}"
    exit 1
fi

echo -e "${GREEN}Configuration file created: $SYSCTL_CONFIG_FILE${NC}"

# Apply the changes immediately
echo -e "${YELLOW}Applying changes to running kernel...${NC}"
if ! sysctl -p "$SYSCTL_CONFIG_FILE" > /dev/null 2>&1; then
    echo -e "${RED}Error: Failed to apply sysctl configuration${NC}"
    exit 1
fi

echo -e "${GREEN}Changes applied successfully${NC}"
echo ""

# Verify new limits
echo -e "${BLUE}New inotify limits (verified):${NC}"
NEW_WATCHES=$(sysctl -n fs.inotify.max_user_watches)
NEW_INSTANCES=$(sysctl -n fs.inotify.max_user_instances)
NEW_QUEUED=$(sysctl -n fs.inotify.max_queued_events)

echo "  max_user_watches:    $NEW_WATCHES"
echo "  max_user_instances:  $NEW_INSTANCES"
echo "  max_queued_events:   $NEW_QUEUED"
echo ""

# Success message
echo -e "${GREEN}✓ inotify limits successfully increased${NC}"
echo ""
echo -e "${YELLOW}Summary:${NC}"
echo "  Config file: $SYSCTL_CONFIG_FILE"
if [[ -n "${BACKUP_FILE:-}" ]]; then
    echo "  Backup:      $BACKUP_FILE"
fi
echo ""
echo -e "${YELLOW}You can now run:${NC}"
echo "  dotnet watch"
echo ""

# Show rollback instructions if backup was created
if [[ -n "${BACKUP_FILE:-}" ]]; then
    echo -e "${YELLOW}To rollback to previous configuration:${NC}"
    echo "  sudo cp $BACKUP_FILE $SYSCTL_CONFIG_FILE"
    echo "  sudo sysctl -p"
    echo ""
fi

# Show verification command
echo -e "${YELLOW}To verify the limits are applied:${NC}"
echo "  sysctl fs.inotify.max_user_watches"
echo "  sysctl fs.inotify.max_user_instances"
echo "  sysctl fs.inotify.max_queued_events"
echo ""
