#!/usr/bin/env bash
# Sourced by dotfiles install.sh: wire per-window keyboard layout into Regolith/i3
# and fix i3status-rust command paths to match DOTFILES_DIR.

configure_keyboard_layout_dotfiles() {
  local dotfiles_dir="${1:?}"
  local dotfiles_home="${2:?}"
  local regolith_i3_d="$dotfiles_home/.config/regolith3/i3/config.d"
  local fragment="$regolith_i3_d/99-dotfiles-keyboard-layout.conf"
  local i3status_conf="$dotfiles_home/.config/regolith3/i3status-rust/config.toml"

  chmod +x \
    "$dotfiles_dir/apps/i3/per-window-layout-daemon.sh" \
    "$dotfiles_dir/apps/i3/layout-cycle.sh" \
    "$dotfiles_dir/apps/i3/layout-bar-status.sh" \
    "$dotfiles_dir/apps/i3/layout-common.sh" \
    2>/dev/null || true

  mkdir -p "$regolith_i3_d"

  cat >"$fragment" <<EOF
# Generated by dotfiles install.sh — per-window keyboard layout (X11 + i3)
exec_always --no-startup-id $dotfiles_dir/apps/i3/per-window-layout-daemon.sh
bindsym \$mod+Mod1+BackSpace exec --no-startup-id $dotfiles_dir/apps/i3/layout-cycle.sh
EOF

  if [ -f "$i3status_conf" ]; then
    sed -i "s|/home/user/git/dotfiles|$dotfiles_dir|g" "$i3status_conf"
  fi
}
