#!/bin/bash
# Use this script to fix blurry text in Electron apps (VSCode, Antigravity, Discord, etc.)
# on Ubuntu when using Wayland with fractional scaling (e.g. 125%).
# It forces these apps to use the native Wayland renderer (Ozone) instead of XWayland.

set -e

echo "Applying High DPI / Fractional Scaling fixes for Electron apps..."

# 1. Systemd User Environment (Standard for Ubuntu/Gnome/Sway sessions)
# This ensures the variable is set for the entire user session, including GUI launchers.
ENV_CONF_DIR="$HOME/.config/environment.d"
mkdir -p "$ENV_CONF_DIR"
ENV_FILE="$ENV_CONF_DIR/90-electron-wayland.conf"

if ! grep -q "ELECTRON_OZONE_PLATFORM_HINT" "$ENV_FILE" 2>/dev/null; then
    echo "ELECTRON_OZONE_PLATFORM_HINT=auto" >> "$ENV_FILE"
    echo "Added ELECTRON_OZONE_PLATFORM_HINT=auto to $ENV_FILE"
else
    echo "Environment variable already set in $ENV_FILE"
fi

# 2. Fish Shell Configuration
# Ensures the variable is available in interactive shell sessions immediately.
FISH_CONF_DIR="$HOME/.config/fish/conf.d"
mkdir -p "$FISH_CONF_DIR"
FISH_FILE="$FISH_CONF_DIR/wayland_electron_fix.fish"

cat > "$FISH_FILE" <<EOF
# Auto-generated by fix_highdpi_scaling.sh
# Forces Electron apps to use Wayland native rendering for sharp text on fractional scaling.
set -gx ELECTRON_OZONE_PLATFORM_HINT auto

# Force specific flags and environment for VS Code to prevent X11 fallback on Sway/Regolith
function code
    set -lx XDG_CURRENT_DESKTOP GNOME
    command code --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland \$argv
end

function vscode
    set -lx XDG_CURRENT_DESKTOP GNOME
    command vscode --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland \$argv
end
EOF
echo "Created $FISH_FILE"

# 3. Patching Desktop Files
# We will proactively find and patch desktop files for known Electron apps.
# This ensures flags are directly embedded in the launcher command.

LOCAL_APPS_DIR="$HOME/.local/share/applications"
mkdir -p "$LOCAL_APPS_DIR"

echo "Searching for desktop files to patch..."

# Array of app names/patterns to look for
APPS=("code" "vscode" "antigravity" "discord" "slack" "google-chrome" "chromium" "electron")

find_and_patch() {
    local PATTERN=$1
    echo "  Looking for desktop files matching: $PATTERN"
    
    # Search in common locations
    find /usr/share/applications /var/lib/snapd/desktop/applications "$HOME/.local/share/applications" \
        -name "*${PATTERN}*.desktop" 2>/dev/null | sort | uniq | while read -r DESKTOP_FILE; do
        
        BASENAME=$(basename "$DESKTOP_FILE")
        LOCAL_TARGET="$LOCAL_APPS_DIR/$BASENAME"
        
        # If it's already in local, usage that.
        # If it's in system, copy to local.
        if [ "$DESKTOP_FILE" != "$LOCAL_TARGET" ]; then
            # Only copy if we don't have a local copy yet (or should we overwrite? 
            # Safer to not overwrite if user customized, but we need to patch it anyway.
            # We'll patch whatever is at LOCAL_TARGET)
            if [ ! -f "$LOCAL_TARGET" ]; then
                 echo "    -> Copying system file to local: $LOCAL_TARGET"
                 cp "$DESKTOP_FILE" "$LOCAL_TARGET"
            else
                 echo "    -> Found local file: $LOCAL_TARGET"
            fi
        else
            echo "    -> Found local file: $LOCAL_TARGET"
        fi
        
        if [ -f "$LOCAL_TARGET" ]; then
            echo "       [*] Patching $BASENAME..."
            
            # FLAGS string to likely solve the issue
            # We use explicit --ozone-platform=wayland as hint=auto is sometimes ignored by older VSCode versions
            FLAGS=" --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland"
            
            # 1. Cleanup: Remove existing flags to prevent duplicates
            sed -i 's| --ozone-platform-hint=auto --enable-features=WaylandWindowDecorations||g' "$LOCAL_TARGET"
            sed -i 's| --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland||g' "$LOCAL_TARGET"
            sed -i 's|env XDG_CURRENT_DESKTOP=GNOME ||g' "$LOCAL_TARGET"
            
            # 2. Insert flags properly
            # Case A: If line contains a % placeholder (like %F, %U), insert flags BEFORE the first % placeholder.
            # Case B: If no % placeholder, append to end of Exec line.
            
            # Step 1: Handle lines with % args
            sed -i -E "s|(^Exec=.*)( %[a-zA-Z].*)|\1$FLAGS\2|" "$LOCAL_TARGET"
            
            # Step 2: Handle lines WITHOUT % args
            if ! grep -q "ozone-platform=wayland" "$LOCAL_TARGET"; then
                 # Append to any Exec= line that doesn't have the flags yet
                 sed -i "/^Exec=/ s/$/$FLAGS/" "$LOCAL_TARGET"
            fi
            
            # 3. Force GNOME desktop environment for code/vscode to prevent X11 fallback on Sway/Regolith
            if [[ "$BASENAME" == *"code"* || "$BASENAME" == *"vscode"* ]]; then
                echo "       [*] Forcing GNOME environment for $BASENAME..."
                if ! grep -q "XDG_CURRENT_DESKTOP=GNOME" "$LOCAL_TARGET"; then
                    # Prepend env variable to Exec line. careful not to mangle other envs if present
                    # If line starts `Exec=env ...` or `Exec=/path/to/bin ...`
                    # We simply insert `env XDG_CURRENT_DESKTOP=GNOME ` after `Exec=`
                    # Note: If `Exec=env FOO=BAR`, it becomes `Exec=env XDG_CURRENT_DESKTOP=GNOME env FOO=BAR` which is valid (env calls env).
                    # Actually better to just normalize `Exec=` to `Exec=env XDG_CURRENT_DESKTOP=GNOME `
                    
                    sed -i 's|^Exec=|Exec=env XDG_CURRENT_DESKTOP=GNOME |' "$LOCAL_TARGET"
                fi
            fi
            
            echo "          -> Patched."
        fi
    done
}

for APP in "${APPS[@]}"; do
    find_and_patch "$APP"
done

# 4. JetBrains IDE Wayland Fix
# JetBrains IDEs (Rider, IntelliJ, GoLand, etc.) are JVM-based (not Electron).
# They run through XWayland by default, which causes blurry rendering with
# fractional scaling. JBR 21+ supports native Wayland via WLToolkit.
# We add -Dawt.toolkit.name=WLToolkit to user-level vmoptions overrides.

echo ""
echo "Applying JetBrains IDE Wayland fixes..."

JETBRAINS_CONF_DIR="$HOME/.config/JetBrains"
if [ -d "$JETBRAINS_CONF_DIR" ]; then
    # Find all user-level vmoptions files (e.g. Rider2025.3/rider64.vmoptions)
    find "$JETBRAINS_CONF_DIR" -name "*64.vmoptions" 2>/dev/null | while read -r VMOPTS_FILE; do
        IDE_DIR=$(basename "$(dirname "$VMOPTS_FILE")")
        if grep -q "awt.toolkit.name=WLToolkit" "$VMOPTS_FILE" 2>/dev/null; then
            echo "  [✓] $IDE_DIR - WLToolkit already configured"
        else
            echo "-Dawt.toolkit.name=WLToolkit" >> "$VMOPTS_FILE"
            echo "  [+] $IDE_DIR - Added WLToolkit for native Wayland rendering"
        fi
    done
else
    echo "  No JetBrains config directory found at $JETBRAINS_CONF_DIR"
    echo "  If you install JetBrains IDEs later, re-run this script."
fi

echo "--------------------------------------------------------"
echo "Fixes applied!"
echo "1. Environment variables set in $ENV_FILE and $FISH_FILE"
echo "2. Desktop file overrides updated in $LOCAL_APPS_DIR"
echo "3. JetBrains IDE vmoptions patched with WLToolkit"
echo ""
echo "Please LOG OUT and LOG BACK IN for full effect."
echo "However, desktop shortcuts should be updated immediately."
echo "For JetBrains IDEs, restart the IDE for the fix to take effect."
echo "--------------------------------------------------------"
