#!/bin/bash
# Use this script to fix blurry text in Electron apps (VSCode, Antigravity, Discord, etc.)
# on Ubuntu when using Wayland with fractional scaling (e.g. 125%).
# It forces these apps to use the native Wayland renderer (Ozone) instead of XWayland.

set -e

echo "Applying High DPI / Fractional Scaling fixes for Electron apps..."

# 1. Systemd User Environment (Standard for Ubuntu/Gnome/Sway sessions)
# This ensures the variable is set for the entire user session, including GUI launchers.
ENV_CONF_DIR="$HOME/.config/environment.d"
mkdir -p "$ENV_CONF_DIR"
ENV_FILE="$ENV_CONF_DIR/90-electron-wayland.conf"

if ! grep -q "ELECTRON_OZONE_PLATFORM_HINT" "$ENV_FILE" 2>/dev/null; then
    echo "ELECTRON_OZONE_PLATFORM_HINT=auto" >> "$ENV_FILE"
    echo "Added ELECTRON_OZONE_PLATFORM_HINT=auto to $ENV_FILE"
else
    echo "Environment variable already set in $ENV_FILE"
fi

# 2. Fish Shell Configuration
# Ensures the variable is available in interactive shell sessions immediately.
FISH_CONF_DIR="$HOME/.config/fish/conf.d"
mkdir -p "$FISH_CONF_DIR"
FISH_FILE="$FISH_CONF_DIR/wayland_electron_fix.fish"

cat > "$FISH_FILE" <<EOF
# Auto-generated by fix_highdpi_scaling.sh
# Forces Electron apps to use Wayland native rendering for sharp text on fractional scaling.
set -gx ELECTRON_OZONE_PLATFORM_HINT auto
EOF
echo "Created $FISH_FILE"

# 3. Patching Desktop Files (Optional but recommended for stubborn apps)
# Some apps might ignore the environment variable or need specific flags explicitly.
# We will create local overrides in ~/.local/share/applications

LOCAL_APPS_DIR="$HOME/.local/share/applications"
mkdir -p "$LOCAL_APPS_DIR"

patch_desktop_file() {
    local APP_NAME=$1
    local DESKTOP_NAME="${APP_NAME}.desktop"
    local SOURCE_PATH=""

    # Find the source desktop file
    if [ -f "/usr/share/applications/$DESKTOP_NAME" ]; then
        SOURCE_PATH="/usr/share/applications/$DESKTOP_NAME"
    elif [ -f "/var/lib/snapd/desktop/applications/$DESKTOP_NAME" ]; then
        SOURCE_PATH="/var/lib/snapd/desktop/applications/$DESKTOP_NAME"
    fi

    if [ -z "$SOURCE_PATH" ]; then
        echo "  [!] Could not find desktop file for $APP_NAME. Skipping manual patch."
        return
    fi

    local TARGET_PATH="$LOCAL_APPS_DIR/$DESKTOP_NAME"

    # Copy if not exists
    cp "$SOURCE_PATH" "$TARGET_PATH"

    # Append flags if not present
    # Flags: --ozone-platform-hint=auto --enable-features=WaylandWindowDecorations
    # We look for Exec lines and append the flags before any % arguments
    
    if ! grep -q "ozone-platform-hint" "$TARGET_PATH"; then
        echo "  [*] Patching $APP_NAME local desktop file..."
        # Regex to insert flags after the executable command
        # Works for standard Exec=/path/to/bin %F
        sed -i -E 's|^(Exec=.*)( %[a-zA-Z].*)?$|\1 --ozone-platform-hint=auto --enable-features=WaylandWindowDecorations\2|' "$TARGET_PATH"
    else
        echo "  [OK] $APP_NAME already has flags in local desktop file."
    fi
}

echo "Checking specific apps for desktop file patching..."
patch_desktop_file "code"
patch_desktop_file "code_code"  # Snap version of VSCode often named this
patch_desktop_file "vscode"
patch_desktop_file "antigravity"
patch_desktop_file "google-chrome"
patch_desktop_file "slack"

echo "--------------------------------------------------------"
echo "Fixes applied!"
echo "1. Environment variables set in $ENV_FILE and $FISH_FILE"
echo "2. Desktop file overrides created in $LOCAL_APPS_DIR"
echo ""
echo "Please LOG OUT and LOG BACK IN for changes to apply to your session."
echo "--------------------------------------------------------"
